### ISSUE TITLE
Copilot new update, the character limit is back 

### ISSUE THREAD

**Issue by simonelmundo** [qzxtu/Copilot-Chat-Pro#5]
Is it possible to make this extension work again with the new copilot update, or is it a lost cause and copilot was patched ?

**Comment by MilkFish1010** [comment]
+1

**Comment by fl2on** [comment]
Hi, it is currently patched in the new version of copilot, the only thing that would still work would be in the bing search bar and copilot in the search tab if your microsoft browser keeps the old version.

Currently it would be complicated to release a new version that would make the extension work.
